### ISSUE TITLE
Generate list of IP addresses and hostnames needed for Kubernetes API server certificate

### ISSUE THREAD

**Issue by qhh0205** [githubixx/ansible-role-kubernetes-ca#5]
I think there is no need to add k8s_worker host to the list when generate the Kubernetes API server certificate. Now as following:
```- name: Generate list of IP addresses and hostnames needed for Kubernetes API server certificate
  set_fact:
    tmpK8sHosts: |
      {% set comma = joiner(",") %}
      {% for item in groups["k8s_controller"] -%}
        {{ comma() }}{{ hostvars[item].ansible_default_ipv4.address }}{{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["k8s_interface"]].ipv4.address }}{{ comma() }}{{ item }}{{ comma() }}{{ hostvars[item]["ansible_hostname"] }}
      {%- endfor %}
      {% for item in groups["k8s_worker"] -%}
        {{ comma() }}{{ hostvars[item].ansible_default_ipv4.address }}{{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["k8s_interface"]].ipv4.address }}{{ comma() }}{{ item }}{{ comma() }}{{ hostvars[item]["ansible_hostname"] }}
      {%- endfor %}
      {% for item in k8s_apiserver_cert_hosts -%}
        {{ comma() }}{{ item }}
      {%- endfor %}
  tags:
    - kubernetes-ca
```
After modifed:
```
- name: Generate list of IP addresses and hostnames needed for Kubernetes API server certificate
  set_fact:
    tmpK8sHosts: |
      {% set comma = joiner(",") %}
      {% for item in groups["k8s_controller"] -%}
        {{ comma() }}{{ hostvars[item].ansible_default_ipv4.address }}{{ comma() }}{{ hostvars[item]["ansible_"+hostvars[item]["k8s_interface"]].ipv4.address }}{{ comma() }}{{ item }}{{ comma() }}{{ hostvars[item]["ansible_hostname"] }}
      {%- endfor %}
      {% for item in k8s_apiserver_cert_hosts -%}
        {{ comma() }}{{ item }}
      {%- endfor %}
  tags:
    - kubernetes-ca
```

**Comment by githubixx** [comment]
You're probably right. I'll have a look. I wanted to change a few things anyways.

**Comment by githubixx** [comment]
I'm currently preparing a new release: https://github.com/githubixx/ansible-role-kubernetes-ca/tree/refactor The patch removes the worker hostnames and IPs from the kube-apiserver certificate (among a few other things). I found a bug in another Ansible role of mine which required to include the worker hostnames and IPs. I fixed that. I guess I'll merge it tomorrow. Tests worked fine on my side so far.

**Comment by qhh0205** [comment]
> I'm currently preparing a new release: https://github.com/githubixx/ansible-role-kubernetes-ca/tree/refactor The patch removes the worker hostnames and IPs from the kube-apiserver certificate (among a few other things). I found a bug in another Ansible role of mine which required to include the worker hostnames and IPs. I fixed that. I guess I'll merge it tomorrow. Tests worked fine on my side so far.

Thanks!

**Comment by qhh0205** [comment]
@githubixx I hava another question about gather facts, i think that  gather facts tasks should be executed before generate cert file, not in ca role playbook. As following
```
- name: Gather hosts facts
  hosts: k8s
  tasks:
    - setup:

- name: Generate cert file
  hosts: k8s_ca
  become: yes
  roles:
    - role: ansible-role-kubernetes-ca
```
If  not gather facts first, that will Error, such as:
```
The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_default_ipv4'
```

**Comment by githubixx** [comment]
Changes are merged now. Thanks for you inputs! Regarding gathering facts: It was already implemented but not very useful TBH :wink: I added a few lines that solves the problem by gathering facts of the affected K8s hosts as the very first task: https://github.com/githubixx/ansible-role-kubernetes-ca/blob/master/tasks/main.yml#L4-L6

**Comment by qhh0205** [comment]
Good pratice!
